name: Docker Image CI

on:
  push:
    branches:
      - main  # Le workflow s'exécutera lorsque vous pusherez sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout le code source de votre dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3 : Connexion à GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Étape 4 : Construire et pousser l'image Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64  # Spécifie les architectures à construire
          tags: ghcr.io/${{ github.repository_owner }}/bot-discord-verif-mail-role:latest  # Remplacez 'my-discord-bot' par le nom que vous voulez donner à votre image
